FROM openjdk:24-slim

RUN dnf update && dnf install -y cron

WORKDIR /app

COPY target/concurso_monitor-0.0.1-SNAPSHOT.jar app.jar

COPY run_scraper.sh /app/run_scraper.sh
RUN chmod +x /app/run_scraper.sh

RUN (crontab -l 2>/dev/null; echo "0 * * * * /app/run_scraper.sh >> /var/log/cron.log 2>&1") | crontab -

CMD cron -f
